### ISSUE TITLE
x64 plugin for x64dbg is not loading

### ISSUE THREAD

**Issue by kolad85** [a1ext/labeless#11]
Latest release will not load up the labeless plugin in x64dbg debugger. This goes for the the x64 only. The 32 bit version is working as it should.

**Comment by a1ext** [comment]
@kolad85 Did you made all installation steps from README ? You should set up protobuf and install labeless module for 64-bit python too. Please, re-check this.

**Comment by kolad85** [comment]
Thanks  a1ext! That was it, I didn't install the protobuf and labeless module for the 64 bit python. Cheers.
