### ISSUE TITLE
Failed to load plugin for x64dbg (32-bit only) on 1.1.0.7 w/Python 2.7

### ISSUE THREAD

**Issue by PsychoSpy** [a1ext/labeless#13]
After following the instructions on the target machine with the latest version (1.1.0.7), the 32-bit version of x64dbg does not load the plug-in properly. Meanwhile, the 64-bit version has no issue.

You can see both the log screen output for both versions here (32-bit on left, 64-bit on right):
![image](https://cloud.githubusercontent.com/assets/1188572/18209044/101642ac-7100-11e6-858f-9e87d519369a.png)

I had this same issue with a previous version attempted earlier (1.1.0.3 specifically).

I've been struggling with trying to get this working to no avail.

I am running on Python 2.7 within a Windows 7 VM.

Thank you for your work on this great set of plugins - I appreciate the time and effort you have put into this valuable project.

**Comment by PsychoSpy** [comment]
Ah crap - ignore this and close it off. It was a 32-bit Python install problem. Writing this out forced my brain to switch into the right gear.

Thanks again for your hard work on this great plugin!

**Comment by a1ext** [comment]
@PsychoSpy You welcome :) Thanks for feedback.
