### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by stonedreamforest** [a1ext/labeless#14]
x64dbg  x64：
` [PLUGIN] Failed to load plugin: labeless_x64dbg.dp64`

x64dbg x32：
```
LL: Labeless::logInitPythonFail: "import labeless as ll" failed.
LL: pluginit: Labeless::initPython() failed
[PLUGIN] pluginit failed for plugin: labeless_x64dbg.dp32
```
labeless vesion：

> labeless_release_full_1.1.0.7.7z

x64dbg vesion ：

> snapshot_2016-09-01_07-38.7z

**Comment by a1ext** [comment]
Did you read the README and done Installation steps for both versions of Python?

**Comment by a1ext** [comment]
[Here](https://www.youtube.com/watch?v=PjV_Lv08E-k) is a video tutorial how to setup.

**Comment by stonedreamforest** [comment]
`C:\WINDOWS\system32>CD C:\Users\Tennn\Desktop\labeless_release_full_1.1.0.7\deploy

C:\Users\Tennn\Desktop\labeless_release_full_1.1.0.7\deploy>C:\Python27\python.exe setup_protobuf.py
Traceback (most recent call last):
  File "setup_protobuf.py", line 35, in <module>
    p_show_protobuf = subprocess.Popen(cmd_show_protobuf, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2]`

**Comment by a1ext** [comment]
What Python versions do you have? Did you start the cmd.exe as an Administrator?

**Comment by stonedreamforest** [comment]
python-2.7.10.msi
https://www.python.org/ftp/python/2.7.10/python-2.7.10.msi

python-2.7.10.amd64.msi
https://www.python.org/ftp/python/2.7.10/python-2.7.10.amd64.msi


Administrator run

**Comment by a1ext** [comment]
Please check is the file "c:\Python27\Scripts\pip.exe" present and runs well

**Comment by stonedreamforest** [comment]
runs well
C:\Users\Tennn\Desktop\labeless_release_full_1.1.0.7\deploy>C:\Python27\Scripts\pip.exe

Usage:
  pip <command> [options]

Commands:
  install                     Install packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  search                      Search PyPI for packages.
  wheel                       Build wheels from your requirements.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --isolated                  Run pip in an isolated mode, ignoring
                              environment variables and user configuration.
  -v, --verbose               Give more output. Option is additive, and can be
                              used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output.
  --log <path>                Path to a verbose appending log.
  --proxy <proxy>             Specify a proxy in the form
                              [user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should
                              attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists:
                              (s)witch, (i)gnore, (w)ipe, (b)ackup.
  --trusted-host <hostname>   Mark this host as trusted, even though it does
                              not have valid or any HTTPS.
  --cert <path>               Path to alternate CA bundle.
  --client-cert <path>        Path to SSL client certificate, a single file
                              containing the private key and the certificate
                              in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine
                              whether a new version of pip is available for
                              download. Implied with --no-index.

C:\Users\Tennn\Desktop\labeless_release_full_1.1.0.7\deploy>

**Comment by a1ext** [comment]
Ok, then just run ```c:\Python27\Scripts\pip.exe install protobuf==2.6.1``` instead of calling setup_protobuf.py

**Comment by stonedreamforest** [comment]
C:\Users\Tennn\Desktop\labeless_release_full_1.1.0.7\deploy>c:\Python27\Scripts\pip.exe install protobuf==2.6.1
You are using pip version 7.0.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting protobuf==2.6.1
  Downloading protobuf-2.6.1.tar.gz (188kB)
    100% |████████████████████████████████| 188kB 2.3MB/s
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from protobuf==2.6.1)
Installing collected packages: protobuf
  Running setup.py install for protobuf
Successfully installed protobuf-2.6.1


What is the next step？

**Comment by a1ext** [comment]
Next, install labeless module (like in the video or in the README) by issuing ```c:\Python27\python.exe setup.py install```

Then, you should do the same for x64-bit Python

**Comment by stonedreamforest** [comment]
Runs successfully.
Thanks for your help - -！
Labelss is  very powerful~
Look forward to the next  next  next  next  next  next  next  next  next  next  next  and numerous times update

**Comment by a1ext** [comment]
You welcome and thanks
