### ISSUE TITLE
Labeless just works with x32dbg but not x64dbg

### ISSUE THREAD

**Issue by trietptm** [a1ext/labeless#17]
Labeless in the latest release "[x64dbg] SDK and testing bundle are updated to snapshot on 2016-09-18_01-22"(labeless_release_full_1.1.0.9.7z) just works with x32dbg but not x64dbg.

![screenshot - 9_28_2016 5_26_30 pm](https://cloud.githubusercontent.com/assets/526959/18910192/1748f866-85a1-11e6-9bb5-eecb6249b7ab.png)
![screenshot - 9_28_2016 5_28_35 pm](https://cloud.githubusercontent.com/assets/526959/18910191/1716749a-85a1-11e6-8c97-c50bfd58873b.png)

**Comment by a1ext** [comment]
Did it work on previous releases? Does it work with x64dbg x64 shipped in release bundle?

**Comment by trietptm** [comment]
No, it doesn't work with the x64dbg x64 shipped in release bundle.

**Comment by trietptm** [comment]
In the previous release (labeless_release_full_1.1.0.8.7z), Labeless doesn't work with both x32dbg and x64dbg.

**Comment by a1ext** [comment]
Could you show me the log tab in x64dbg, maybe there is some error information

**Comment by trietptm** [comment]
Here it is:
> Initializing wait objects...
> Initializing debugger...
> Initializing debugger functions...
> Setting JSON memory management functions...
> Initializing capstone...
> Initializing Yara...
> Getting directory information...
> Start file read thread...
> Symbol Path: C:\TEST\labeless_release_full_1.1.0.9\x64dbg\x64\symbols
> Allocating message stack...
> Initializing global script variables...
> Registering debugger commands...
> Registering GUI command handler...
> Registering expression functions...
> Registering Script DLL command handler...
> Starting command loop...
> Loading plugins...
> [PLUGIN] command "allocex" registered!
> LL: Labeless::logInitPythonFail: "import labeless as ll" failed.
> LL: pluginit: Labeless::initPython() failed
> [PLUGIN] pluginit failed for plugin: labeless_x64dbg.dp64
> Handling command line...
> Initialization successful!
> Mnemonic help database loaded!
> Error codes database loaded!
> Exception codes database loaded!
> NTSTATUS codes database loaded!
> Reading notes file...
> File read thread finished!

**Comment by a1ext** [comment]
Did you set up labeless python module and protobuf for python x64?

**Comment by trietptm** [comment]
Ah, I just setup labeless python module and protobuf for python x32 only :D .
After I setup for Python x64, Labeless works with x64dbg now :+1: .
