### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by stonedreamforest** [a1ext/labeless#19]
ida 6.8:
Labeless::loadImportTable: storage::loadExternSegData() failed

**Comment by a1ext** [comment]
I is not an error, I'll remove that noisy message, thanks.

**Comment by stonedreamforest** [comment]
new problem：

No analysis
![13](https://cloud.githubusercontent.com/assets/16742566/19150913/3e57f608-8bfc-11e6-876e-bd45f9230322.png)

**Comment by stonedreamforest** [comment]
labeless(labeless_release_full_1.1.0.9)

ida(6.8)：
Labeless: do sync all now...
Labels: 895, comments: 0
RPC Thread: OK, tasks left: 0

x64dbg（oct 6 2016 ）：
LL: Labeless::onClientSockAccept: Connected from: 127.0.0.1:53208
LL: socket 000011CC accepted
LL: Labeless::onClientSockRead: Received 18389 bytes of 18389.
LL: Labeless::onClientSockBufferReceived: new request pushed { jobId: 8, bkg: 0, finished: 0 }
LL: Labeless::serverThread: jobId 8 socket 000011CC Response sent, len: 0x0000000A
LL: Labeless::serverThread: jobId 8 is removed

**Comment by a1ext** [comment]
@stonedreamforest Hi, I see, you have loaded module at different addresses, but you was not adjusted the remote module base in the Labeless settings view.

**Comment by stonedreamforest** [comment]
Successfully modified.

next problem：
![1](https://cloud.githubusercontent.com/assets/16742566/19151291/77a2e970-8bfe-11e6-9cbc-509942c15852.png)

**Comment by a1ext** [comment]
You should check "Function local vars (structs only) in the settings view.

**Comment by stonedreamforest** [comment]
I have chosen it ，but No analysis yet

**Comment by stonedreamforest** [comment]
![222](https://cloud.githubusercontent.com/assets/16742566/19151967/3ae40be6-8c02-11e6-9eff-1632a5850686.png)

Thanks for your help(-_-)

**Comment by a1ext** [comment]
Yep, the are displayed as comments...
You welcome
