### ISSUE TITLE
Olly part doesn't show up in the plugin menu

### ISSUE THREAD

**Issue by minyen** [a1ext/labeless#2]
First of all, I appreciated for your work!

I download the link on the bottom of the Github page and try to install it.
But the plugin doesn't show up in the plugin menu.
I also checked the log, but nothing showed up.

I've tried ollydbg 108b, 110 and 201 but all of them don't work either.

So here comes my questions:

1. What version of ollydbg is compatible with Labeless?
2. If I only want to use (instead of build) the plugin, is Visual Studio 2012 (or newer) necessary?

**Comment by a1ext** [comment]
Thank you.
1. That archive contains only plugins for **OllyDbg 1.10** as debug backend.
So, for installation instructions see corresponding section [there](https://github.com/a1ext/labeless#installation). One small change is to use ```setup_protobuf.py``` instead of ```.bat```. Also, the main (in ```%PATH%```) python interpreter should be 32-bit one.
2. Olly-side plugin doesn't require Visual Studio to be installed. 

I'm working on implementation of **OllyDbg 2.01** and **x64_dbg** (including 64-bit) backends at the moment.

**Comment by minyen** [comment]
Thanks for the quick reply!

I know why it crashed on OllyDbg 1.10 now.
It's the version of Python. 
The Olly part works on version below 2.7.10, but with the latest version which is 2.7.11, it will crash when loading.

**Comment by a1ext** [comment]
Thanks
I'll check that soon. Do you know where exactly it crashes?

**Comment by minyen** [comment]
Sorry, I just found this out by trial and error.
With 2.7.11, the OllyDbg just flashed then disappeared after launch.

I'm using Windows XP SP3 32-bit.

**Comment by a1ext** [comment]
Does IDAPython initialize successful in your IDA at the same machine?

**Comment by minyen** [comment]
No, it shows "IDAPython: importing "site" failed".
Same thing here, with python 2.7.10, there is no any error message.

**Comment by a1ext** [comment]
Please, check is labeless works in python 2.7.10.

**Comment by a1ext** [comment]
I found the bug in Python 2.7.11 and opened the [issue](http://bugs.python.org/issue26998)
So, let me know is Labeless works for you with Python 2.7.10.

P.S. Soon, I'll make build of Labeless with support of OllyDbg 2.0 and x64dbg (with 64-bit app support).

**Comment by minyen** [comment]
It works!
I'm using Python 2.7.10, OllyDbg 1.10 and IDA Pro 6.8.
Appreciate for your work!
