### ISSUE TITLE
Function local vars

### ISSUE THREAD

**Issue by trietptm** [a1ext/labeless#20]
Hi, I recently update labeless to the latest version and see that the local vars of functions are not synced from IDA to OllyDbg like the previous versions of labeless. I think it's more convenient to sync all function local vars (not only the structs only ones).

![screenshot - 10_1_2016 9_48_38 am](https://cloud.githubusercontent.com/assets/526959/19011324/4aff9d8c-87bc-11e6-9a3c-49823d3fb3c0.png)

**Comment by AlexWMF** [comment]
I did that, but got a lot of noisy comments, which were useless until you reverse all the database

**Comment by a1ext** [comment]
I did that, but got a lot of noisy comments, which were useless until you reverse all the database :)

**Comment by trietptm** [comment]
I think you should leave it as an option, it's one of the most useful feature of Labeless.

**Comment by a1ext** [comment]
Do you want all the local vars or only non-dummy named?

**Comment by trietptm** [comment]
I want all the local vars, it's better than the vars displayed only as numbers in OllyDbg.

**Comment by pedrib** [comment]
@a1ext why do you think they were useless? I agree with @trietptm, it's an awesome feature.

**Comment by a1ext** [comment]
resolved
