### ISSUE TITLE
load plugin fails.

### ISSUE THREAD

**Issue by cxj98** [a1ext/labeless#22]
LL: Labeless::logInitPythonFail: "import labeless as ll" failed.
LL: pluginit: Labeless::initPython() failed
[插件] 插件函数pluginit失败: labeless_x64dbg.dp32

load fails, how does it work? none-English character not support?

**Comment by a1ext** [comment]
Did you perform the installation steps, which are described in the Readme?
I mean she up protobuf and Labeless Python module.

суббота, 15 октября 2016 г. пользователь cxj98 написал:

**Comment by anaivebird** [comment]
also that problem:
see https://github.com/a1ext/labeless/issues/52
