### ISSUE TITLE
Labeless for linux missing

### ISSUE THREAD

**Issue by kolad85** [a1ext/labeless#26]
When I download the release I cannot find the labeless_ida.plx and labeless_ida.plx64 files. Where have they gone?

**Comment by a1ext** [comment]
@kolad85 Yes, you are right. It just had no time to do this. 
I've just re-uploaded 1.1.2.1 build with .plx/plx64 files, you can find them [here](https://github.com/a1ext/labeless/releases/tag/v_1_1_2_1).

**Comment by kolad85** [comment]
You are a start! Thank you very much!
