### ISSUE TITLE
cannot work with BreakModule

### ISSUE THREAD

**Issue by emc2314** [a1ext/labeless#27]
I've setup protobuf & labeless with python 2.7 32bit.
Then I copied the corresponding plugin folder to ollydbg and x64dbg
I can safely use ollydbg with labeless as well as the given x64dbg.
But whenever I run my own x64dbg(32bit) it just stuck and the crash.
Deleting labeless_x64dbg.dp32 solves that problem but obviously we cannot do that as a workaround.
So any ideas? I would appreciate every help.
Thank you

**Comment by a1ext** [comment]
Hi @emc2314, thanks for using Labeless.
Could you show me your x64dbg version/build number/date.
I've just checked the latest shapshot version from `3 Aug 2017` and the Labeless doesn't crash in x64dbg(x32).
![image](https://user-images.githubusercontent.com/14978853/28976879-5bdb1af4-7948-11e7-8c3b-e0f8501ac1c4.png)


Please, provide more information about your x64dbg(32bit) you are using.

**Comment by emc2314** [comment]
Firstly I would like to express my grateful thanks for your reply.
Please forgive my rudeness, I didn't test it fully before open this issue.
It turns out that one of my plugins, BreakModule, is not compatilble with labeless.
So I decide to deprecate that one and have labeless installed.
Sorry agiain.
