### ISSUE TITLE
Can you provide a IDA7.0 version of the plugin

### ISSUE THREAD

**Issue by nihuai** [a1ext/labeless#32]
Will it be compatible with the new version:IDA7.0

**Comment by a1ext** [comment]
Hi @nihuai, you can check the test build [here](https://github.com/a1ext/labeless/files/1318406/labeless_ida_70_for_test.zip)

I'll prepare the full release soon (need to do some of refactoring).

**Comment by a1ext** [comment]
Labeless 1.1.2.1 for IDA7 for Linux with ABI fix: 
[labeless_1.1.2.1_ida7_x64_gcc_abi_fix0.zip](https://github.com/a1ext/labeless/files/1404194/labeless_1.1.2.1_ida7_x64_gcc_abi_fix0.zip)

**Comment by nihuai** [comment]
Hello, my platform is win7.
The dynamic debugging tool is x64dbg.

**Comment by a1ext** [comment]
@nihuai 
Does this build work for you: [labeless_ida_70_for_test.zip](https://github.com/a1ext/labeless/files/1318406/labeless_ida_70_for_test.zip)?

**Comment by nihuai** [comment]
@a1ext 
The x64dbg plugin didn't find it

**Comment by a1ext** [comment]
x64dbg x64? did you set up `protobuf` and `labeless` python module as said in the README?
Show me x64dbg logs

**Comment by nihuai** [comment]
According to the video.
Install only python modules.
There is no x64dbg setup on github

**Comment by nihuai** [comment]
![image](https://user-images.githubusercontent.com/22935890/31890076-8bbc83c2-b834-11e7-98ee-4765fe74a73d.png)
README. Md？

**Comment by a1ext** [comment]
no, [Debug-backend setup](https://github.com/a1ext/labeless#usage-of-precompiled-binaries-release-version)

**Comment by a1ext** [comment]
try x64dbg from the release folder first, if it is work then you can copy labeless plugins from x64dbg to your x64dbg

**Comment by a1ext** [comment]
I mean this one 
![image](https://user-images.githubusercontent.com/14978853/31890368-91d2e1e4-b80b-11e7-97b7-7611ff679f57.png)

**Comment by nihuai** [comment]
![image](https://user-images.githubusercontent.com/22935890/31891497-2f24c85e-b839-11e7-963a-1fb15c57f721.png)
![image](https://user-images.githubusercontent.com/22935890/31891526-3eefab14-b839-11e7-8c98-e5cff9d5bf31.png)
![image](https://user-images.githubusercontent.com/22935890/31891545-4e437320-b839-11e7-9989-296bf48723ea.png)

**Comment by nihuai** [comment]
![image](https://user-images.githubusercontent.com/22935890/31891714-ce70afc2-b839-11e7-91e6-c1ef561cf424.png)
![image](https://user-images.githubusercontent.com/22935890/31891784-fb4393f2-b839-11e7-8e0c-69e6ec6de236.png)

**Comment by a1ext** [comment]
@nihuai you need to copy labeless plugins from release folder,  to yours:

 `x64dbg\x32\plugins\labeless_x64dbg.dp32` -> `your_x64dbg\x32\plugins\labeless_x64dbg.dp32`
 `x64dbg\x64\plugins\labeless_x64dbg.dp64` -> `your_x64dbg\x64\plugins\labeless_x64dbg.dp64`

**Comment by nihuai** [comment]
![image](https://user-images.githubusercontent.com/22935890/31891953-63fab858-b83a-11e7-9062-468a840b95b3.png)

**Comment by nihuai** [comment]
I downloaded the wrong package：labeless-master

**Comment by a1ext** [comment]
yes, the source tree doesn't contain precompiled Labeless binaries

**Comment by nihuai** [comment]
![image](https://user-images.githubusercontent.com/22935890/31894207-4b38cec6-b840-11e7-95af-aec068d130ea.png)
The test tomorrow
Sleep, thank you for your help

**Comment by a1ext** [comment]
> Rejected by IP Filter
Try to disable IP filter or update it to match your client IP ("127.0.0.1)

**Comment by nihuai** [comment]
Thanks for your help
Manually set up IP, IDA connection is successful，Debugger synchronization successful.
But there's a little problem here.
every time  open x64dbg, need to manually set it up.

**Comment by a1ext** [comment]
>every time open x64dbg, need to manually set it up.

That's strange. I just put empty string in "Set IP Filter" dialog and then it allows to connect from any IP.

Use case:
* Set "127.0.0.1" IP filter:
 
![image](https://user-images.githubusercontent.com/14978853/31928894-82719686-b8a2-11e7-9c9c-09c7f4558d7d.png)
![image](https://user-images.githubusercontent.com/14978853/31928914-8e499062-b8a2-11e7-96a0-72a99847ac40.png)

* Then set empty string "" to allow any IP

![image](https://user-images.githubusercontent.com/14978853/31928975-c8dc07e6-b8a2-11e7-91ae-71aa5b65410e.png)

![image](https://user-images.githubusercontent.com/14978853/31928968-bc082b30-b8a2-11e7-8e1b-281d5383b2fb.png)

And this configuration works for me even after x64dbg restart.

Probably you don't have an access to write to x32dbg.ini/x64dbg.ini?

**Comment by nihuai** [comment]
@a1ext Just Just tested, ida7.0 prompts the connection to fail, but does not affect the use
