### ISSUE TITLE
The IDA7.0 plug-in test version, error

### ISSUE THREAD

**Issue by nihuai** [a1ext/labeless#34]
@a1ext
Debug 32 bit programs in 64-bit IDA7.0（ida.exe）:
Just tested, ida7.0 prompts the connection to fail, but does not affect the use.
It's a strange question, and I almost give up using it

new problem:
Debug 64 bit programs in 64-bit IDA7.0（ida64.exe）:
prompts connection failure,Click hand sync.
No response，The program card to death

Debug 32 bit programs in 64-bit IDA7.0（ida64.exe）:
prompts connection failure,Click hand sync.
Log prompt Received data, but not displayed

**Comment by a1ext** [comment]
@nihuai Could you explain the problem? I don't understand it.

**Comment by nihuai** [comment]
@a1ext 
The IDA7.0 directory has two executable files: IDA. exe and ida64.exe.
I used IDA. exe and x32dbg to synchronize 32-bit programs.
Find that connection failures can also be synchronized, and manually clicking is ok.
![image](https://user-images.githubusercontent.com/22935890/32215035-bce6dee8-be5b-11e7-89a8-d0b78487ddf8.png)
![image](https://user-images.githubusercontent.com/22935890/32215113-f9a03b40-be5b-11e7-82d3-9be6af3dece3.png)

However, I use ida64. exe to debug 32-bit or 64-bit programs, which can cause problems.
![image](https://user-images.githubusercontent.com/22935890/32215242-658cb090-be5c-11e7-8aa7-32feb723e15e.png)
![image](https://user-images.githubusercontent.com/22935890/32215287-891027f4-be5c-11e7-92eb-14a5257b71ce.png)

**Comment by nihuai** [comment]
Unable to upload images, I copied the code：That is, receiving data but not showing it
00401000 | push ctf2017_fpc.41B06C
00401005 | call ctf2017_fpc.413D42
0040100A | add esp,4 
0040100D | mov dword ptr ds:[41B034],2
00401017 | call ctf2017_fpc.401050
0040101C | call ctf2017_fpc.401090
00401021 | call ctf2017_fpc.4010E0
00401026 | mov eax,dword ptr ds:[41B034]
0040102B | test eax,eax
0040102D | jne ctf2017_fpc.40103F
0040102F | push ctf2017_fpc.41B05C
00401034 | call ctf2017_fpc.413D42
00401039 | add esp,4
0040103C | xor eax,eax
0040103E | ret

**Comment by nihuai** [comment]
Below is the 64-bit application I used with ida64. exe:It's stuck
![image](https://user-images.githubusercontent.com/22935890/32216332-ba31649e-be5f-11e7-96d5-4eafebf646b9.png)

**Comment by a1ext** [comment]
Could you show me the full log from x64dbg?

**Comment by nihuai** [comment]
`Labeless::Labeless
Labeless: Python initialized... OK
Possible file format: MS-DOS executable (EXE) (D:\IDA_7.0\loaders\dos64.dll)
Possible file format: Portable executable for 80386 (PE) (D:\IDA_7.0\loaders\pe64.dll)

  bytes   pages size description
--------- ----- ---- --------------------------------------------
   262144    32 8192 allocating memory for b-tree...
    98304    12 8192 allocating memory for virtual array...
   262144    32 8192 allocating memory for name pointers...
-----------------------------------------------------------------
   622592            total memory allocated

Loading file 'C:\Users\nihuai\Desktop\hello.exe' into database...
Detected file format: Portable executable for 80386 (PE)
Loading processor module D:\IDA_7.0\procs\pc64.dll for metapc...OK
Autoanalysis subsystem has been initialized.
  0. Creating a new segment  (0000000000401000-0000000000403000) ... ... OK
  1. Creating a new segment  (0000000000403000-0000000000404000) ... ... OK
  2. Creating a new segment  (0000000000404000-0000000000405000) ... ... OK
Reading imports directory...
  3. Creating a new segment  (0000000000403208-0000000000404000) ... ... OK
Plan  FLIRT signature: Microsoft VisualC 2-14/net runtime
autoload.cfg: vc32rtf.sig autoloads mssdk.til
Assuming __cdecl calling convention by default
Type library 'mssdk' loaded. Applying types...
Types applied to 21 names.
Plan  FLIRT signature: MFC 3.1-14.0 32bit
autoload.cfg: vc32mfc.sig autoloads mssdk.til
main() function at 40202E, named "_WinMain@16"
Marking typical code sequences...
Flushing buffers, please wait...ok
File 'C:\Users\nihuai\Desktop\hello.exe' has been successfully loaded into the database.
__cdecl RpcThreadWorker::RpcThreadWorker(class QT::QObject *)
__cdecl JediCompletionWorker::JediCompletionWorker(class QT::QObject *)
IDA is analysing the input file...
You may start to explore the input file right now.
RPC Thread: util::python::jedi::init() failed, error: Cannot import `jedi` module

__cdecl JediCompletionWorker::~JediCompletionWorker(void)
---------------------------------------------------------------------------------------------
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] 
IDAPython 64-bit v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
---------------------------------------------------------------------------------------------
Type library 'vc6win' loaded. Applying types...
Types applied to 1 names.
Using FLIRT signature: Microsoft VisualC 2-14/net runtime
Using FLIRT signature: MFC 3.1-14.0 32bit
Propagating type information...
Function argument information has been propagated
The initial autoanalysis has been finished.`

**Comment by a1ext** [comment]
Hi @nihuai,
I found the problem - x64dbgpy plugin. When it is installed, the Labeless behaves strange

**Comment by a1ext** [comment]
Comments aren't visible in the "Comments" view because I do sync with `manual=False` flag, so I think need to make this configurable.

**Comment by a1ext** [comment]
What about version check - it conflicts with x64dbgpy's `x64dbgpy.hooks.OutputHook` implementation, it doesn't call `self.__original_stream` so any output to `stdout`/`stderr` isn't visible to Labeless

**Comment by nihuai** [comment]
Ok, when will ida7.0 plug-in be officially released

**Comment by a1ext** [comment]
There is big solution refactoring and need to fix few issues. I think, I will release it step-by-step like beta versions, etc. The worst case is by the end of November.

**Comment by nihuai** [comment]
@a1ext I recommend the latest version of x64dbg，It improved a lot from two months ago

**Comment by PwndDepot** [comment]
@a1ext I can't seem to find the compiled binary for ida7, is it released as well or just source?

**Comment by a1ext** [comment]
@nihuai It is there, in the release bundle (inside a folder `IDA7X`):
![image](https://user-images.githubusercontent.com/14978853/41224471-3dce33a8-6d75-11e8-971a-705ebdfe8879.png)

**Comment by a1ext** [comment]
@nihuai Don't forget to install fresh python module, you have to uninstall the old one with `pip`:
```
pip uninstall labeless
```
and then answer `y` when it prompts to confirm

and then install the fresh one from PyPI:
```
pip install labeless
```

In case you don't have an Internet, you could install it manually. Download the release bundle and open a command shell inside that folder:
```
cd c:\labeless_release_full_1.1.2.48\deploy
python setup_protobuf.py
pip install labeless-1.1.2.48-py2.py3-none-any.whl
```

**Comment by gkfnf** [comment]
I just downloaded the latest release version.  And figured out the folder IDA7X doesn't exist.  There must be something wrong.

**Comment by a1ext** [comment]
show me the content of the archive you have and its sha256 sum

**Comment by a1ext** [comment]
@gkfnf You have to use this [link](https://github.com/a1ext/labeless/releases) 1.1.2.48 is the latest. You didn't see it because it is a pre-release.

**Comment by gkfnf** [comment]
I checked again. And I found that it's not the file's problem.  It's the link's problem. the latest version on https://github.com/a1ext/labeless﻿/latest.  If I input this link in the explorer, it will auto jump to the https://github.com/a1ext/labeless/releases/tag/v_1_1_2_1.  That's really weird.

**Comment by gkfnf** [comment]
And I just can't visit the right page

**Comment by a1ext** [comment]
@gkfnf currently it should work, could you check it?

**Comment by gkfnf** [comment]
And I found the point.  It's my agent caused this problem. Once I shut down the agent. It works.

**Comment by a1ext** [comment]
@gkfnf I made the `pre-release` -> `release` change :) Now the old link must work
