### ISSUE TITLE
Update precompiled binary x64dbg version

### ISSUE THREAD

**Issue by disconnect3d** [a1ext/labeless#39]
Hey,

Any chance of updating precompiled binary x64dbg version? It is still on a version from 2016...

Thanks,
Disconnect3d

**Comment by a1ext** [comment]
@disconnect3d I'll try to find some time to do this. Currently the main problem is free time.

**Comment by a1ext** [comment]
Done, [v 1.1.2.65](https://github.com/a1ext/labeless/releases/tag/v_1_1_2_65)
