### ISSUE TITLE
Question: Olly Advanced and labeless

### ISSUE THREAD

**Issue by trietptm** [a1ext/labeless#4]
Does labeless need Olly Advanced (advancedolly.dll) as I see it's included in the release?

**Comment by a1ext** [comment]
I had problems with OllDbg 1.10 on win7 x64. I don't remember what exactly was, may be single-step problems or It crashed. Anyway, the Olly Advanced fixes these issues.

**Comment by trietptm** [comment]
It's the "Single-step break" exception problem in Windows 7 x64, thank you :) .
