### ISSUE TITLE
x86 plugins can not be loaded

### ISSUE THREAD

**Issue by AlphaFase** [a1ext/labeless#43]
Win10 x86 plug-ins can not be loaded normally, olldbg and x64dbg

**Comment by a1ext** [comment]
What installation steps did you perform, give me more information, attach ollydbg/x64dbg logs.

**Comment by AlphaFase** [comment]
Plugins are not loaded, where log information is available.

**Comment by a1ext** [comment]
@AlphaFase, do you understand me? Have you performed installation steps from README? Probably, you need at least to install `labeless` python module as well as to specify `plugins` directory for OllyDBG. x64dbg should work out of the box. I checked on the latest Win 10 x64:
![image](https://user-images.githubusercontent.com/14978853/45571553-4434ed00-b86f-11e8-8456-6bd1200a3888.png)
![image](https://user-images.githubusercontent.com/14978853/45571624-81997a80-b86f-11e8-9eb1-fc4cd27ce94a.png)

**Comment by a1ext** [comment]
So, I'm closing the issue. If are still have the problem, write here and reopen the issue.
