### ISSUE TITLE
IDA7 Linux plugin

### ISSUE THREAD

**Issue by gljiva** [a1ext/labeless#44]
Hi,
In the docs it's mentioned that Linux is supported but couldn't find any Linux IDA plugins in release files or notes on how to build the plugin on Linux?
Is the Linux IDA supported with the current version and could you provide some notes on how to build the plugin?

Thanks!

**Comment by a1ext** [comment]
Hi @gljiva, 
It is supported, but I don't have an IDA for Linux, so I cannot test it myself... I can provide binaries if you want to try it, but I don't guarantee that it will work 100%...

There are few files:
![image](https://user-images.githubusercontent.com/14978853/45934079-7649fb80-bfa1-11e8-9f3e-3f5cca376ba2.png)

Installation steps:
* copy `labeless_ida_70.so` and `labeless_ida_70_64.so` files to your IDA's `plugins` directory
* copy `libprotobuf.so.9` to your IDA home (folder, whre `ida` or `ida64` resides)


[1.1.2.85-linux.zip](https://github.com/a1ext/labeless/files/2409256/1.1.2.85-linux.zip)

**Comment by a1ext** [comment]
P.S. I've just added this build to the latest release...

**Comment by a1ext** [comment]
Ok, I'm closing the issue. In case you have problems - just re-open it.
