### ISSUE TITLE
Chinese comments cannot be synchronized

### ISSUE THREAD

**Issue by taodaqiao** [a1ext/labeless#47]
Chinese comments cannot be synchronized

**Comment by a1ext** [comment]
Hi @taodaqiao, what is your set up?

**Comment by taodaqiao** [comment]
@a1ext 测试注释同步 such comments cannot be synced to x32dbg

**Comment by a1ext** [comment]
@taodaqiao ok, I got the problem. 

BTW, are you able to set Chinese comment in OllyDbg2 as well (because I've unsuccessfully tried to do that on English default language Windows 7)? I'm trying to understand is this problem affects OllyDbg 1/2 as well.

**Comment by a1ext** [comment]
@taodaqiao Fixed. Both binaries and `labeless` python module have changed. You have to upgrade them all, prebuilt binaries are at [Appveyor](https://ci.appveyor.com/project/a1ext/labeless/builds/20331491/artifacts) - you can use them until new release is out.

I'm closing the issue, in case there are still some problems feel free to reopen it.

**Comment by taodaqiao** [comment]
@a1ext Version 1.1.2.96
X64dbg test Notes Unicode strings can be synchronized but function names cannot be synchronized.
Olly1 test all symbols cannot be synchronized

**Comment by a1ext** [comment]
> X64dbg test Notes Unicode strings can be synchronized but function names cannot be synchronized.
As I know IDA doesn't allow me to enter your test string:
![image](https://user-images.githubusercontent.com/14978853/48713935-981ed200-ec22-11e8-8e91-2e44cdd932ff.png)

**Comment by a1ext** [comment]
@taodaqiao it will be quicker to talk in Telegram https://t.me/labe1ess

**Comment by a1ext** [comment]
> @a1ext Need to set IDA cfg/ida.cfg CULTURE="all"

ok, another one question: does OllyDBG 1.10 allows you to manually put unicode string in label/comment for you?
When I try that on English machine it just puts "????" instead of test string:
![image](https://user-images.githubusercontent.com/14978853/48841814-96304c80-eda3-11e8-87e5-a513695b18c7.png)

**Comment by a1ext** [comment]
@taodaqiao I has just fixed, could you re-check? I decided to encode labels/comments in OllyDBG 1.10 with a system ANSI (ACP) code page, so if you have a Chinese OS, it have to work then.

**Comment by a1ext** [comment]
> OD1.10
> ![od1 1](https://user-images.githubusercontent.com/33372680/48928705-96078c80-ef1c-11e8-9095-222c819e001e.png)
> IDA7.0
> ![ida7 0](https://user-images.githubusercontent.com/33372680/48928729-bf281d00-ef1c-11e8-8d9a-6e26a2db6f90.png)
> @a1ext OllyDBG 1.10 gb2312(936) code page

is there any problem, I don't understand the pictures?
