### ISSUE TITLE
could not show labeless on od plugin drop down menu

### ISSUE THREAD

**Issue by anaivebird** [a1ext/labeless#52]
### Environment
Windows 10 64bit
python 2.7 32bit+64bit

#### Debugger-side information

| Question                         | Answer
|----------------------------------|--------------------
| OS version (client)              | win10 10
| Plugin version                   | lastest 1.1.2.85
| `labeless` python module version | use `pip show labeless` command
g1.10, OllyDbg 2.01, x64dbg) , Remote memory dumping tool (including x64-bit), Python scripting tool
Home-page: https://github.com/a1ext/labeless
Author: Aliaksandr Trafimchuk
Author-email: a13x4nd3r.t@gmail.com
License: CC-BY-NC-4.0
Location: c:\python27\lib\site-packages
Requires: protobuf, setuptools

| Debugger type                    | 
I tested OllyDbg 1.10, OllyDbg 2.01, x64dbg-x32, x64dbg-x64, all of them could not show labeless on plugin drop down menu

### Problem Description
Describe the problem/bug as clearly as possible.

Could not show labeless on plugin drop down menu. I have tested OllyDbg 1.10, OllyDbg 2.01, x64dbg-x32, x64dbg-x64, all of them failed to show labeless

### Steps to Reproduce
1. download latest release from github
1. run any of 4 debugger after unzip 

### Complementary information
I have set environment variablable both for C:\Python27 and C:\Python27_32
and in cmd, python could be used.

python setup_protocol.py also succeed:

**Comment by anaivebird** [comment]
I found error after import labeless:

>>> import labeless
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\labeless\__init__.py", line 16, in <module>
    import py_olly
  File "C:\Python27\lib\site-packages\labeless\py_olly.py", line 11, in <module>
    import _py_olly
ImportError: No module named _py_olly

**Comment by anaivebird** [comment]
LL: Labeless::logInitPythonFail: "import labeless as ll" failed.
LL: Traceback (most recent call last):
LL:   File "C:\Python27\lib\site-packages\labeless\backend\__init__.py", line 17, in get_backend
LL:     module = __import__(name, globals(), locals(), ["dummy"], -1)
LL:   File "C:\Python27\lib\site-packages\labeless\backend\x64dbg\__init__.py", line 12, in <module>
LL:     from utils import *
LL:   File "C:\Python27\lib\site-packages\labeless\backend\x64dbg\utils.py", line 15, in <module>
LL:     import ctypes as C
LL:   File "C:\Python27\Lib\ctypes\__init__.py", line 7, in <module>
LL:     from _ctypes import Union, Structure, Array
LL: ImportError: DLL load failed: %1 ������Ч�� Win32 Ӧ�ó�����
LL: Traceback (most recent call last):
LL:   File "<string>", line 1, in <module>
LL:   File "C:\Python27\lib\site-packages\labeless\__init__.py", line 34, in <module>
LL:     all_names = getattr(LB, '__all__') if hasattr(LB, '__all__') else (key for key in LB.__dict__ if not key.startswith('_'))
LL: AttributeError: 'NoneType' object has no attribute '__dict__'
LL: pluginit: Labeless::initPython() failed

**Comment by a1ext** [comment]
Hello, seems like you have mess with your python set up. try to uninstall all of them and install following this video tutorial https://www.youtube.com/watch?v=r5JsDk1SYoM&ab_channel=alext

**Comment by anaivebird** [comment]
Thx. It finally worked after installing python 2.7.10:
https://www.python.org/ftp/python/2.7.10/python-2.7.10.msi
https://www.python.org/ftp/python/2.7.10/python-2.7.10.amd64.msi
