### ISSUE TITLE
how to see segments of code imported by labeless

### ISSUE THREAD

**Issue by anaivebird** [a1ext/labeless#53]
I import several segments from memory using labeless. They are from different dlls.

I want to add ida segments to discriminate them. How to  implement that?

Theoritically, add segments in ida could be done by labeless automatically, but that not happen. Does that implemented in labeless?

Thanks for your reply yesterday.

**Comment by anaivebird** [comment]
Another question is why labeless dumped by labeless are identified as data, not code. Shouldn't that convert to code be automatical?

**Comment by a1ext** [comment]
> I want to add ida segments to discriminate them. How to implement that?
Hello, I didn't get this.

**Comment by a1ext** [comment]
> Another question is why labeless dumped by labeless are identified as data, not code. Shouldn't that convert to code be automatical?

When you dump some memory - you can right click on it and do "Import As RWE" - then the new segment in IDA will have RWE flags. The data in the segment is not being forced as code because there is no 100% working way to determine that

**Comment by anaivebird** [comment]
Thanks for reply again.  I mean the ida segments management here.
![image](https://user-images.githubusercontent.com/29398611/106741538-c7c92180-6656-11eb-9a08-a90fd096900a.png)

**Comment by anaivebird** [comment]
Sorry, segments actually show up on segment windows, so I close the issue
