### ISSUE TITLE
Labeless works for ida 7.0 but not show on ida 7.5

### ISSUE THREAD

**Issue by anaivebird** [a1ext/labeless#55]

**Comment by a1ext** [comment]
yes, use Python 2 and the latest build from Appveyor

**Comment by anaivebird** [comment]
thx，and sounds like need to enable python2 plugin in ida 7.5 since it closed it by default

**Comment by anaivebird** [comment]
Hi, sorry for taking your time again:

labeless not work for ida 7.5 for me, but on the same machine labeless with ida 7.0 works, so I think my python2.7 is installed correctly.

Error info:
LoadLibrary(C:\Users\Administrator\Desktop\IDA PRO 7.5 (x86, x64, ARM, ARM64)\plugins\labeless_ida_70.dll) error: The specified module could not be found.
C:\Users\Administrator\Desktop\IDA PRO 7.5 (x86, x64, ARM, ARM64)\plugins\labeless_ida_70.dll: can't load file

**Comment by anaivebird** [comment]
Solved, just make sure install python2.7.10(32 bit into c:\python27  64bit into python27x64) only add c:\python27 to path.

if not solved, see more on https://www.hex-rays.com/blog/ida-and-common-python-issues/
