### ISSUE TITLE
Auto close all windows instead of open them

### ISSUE THREAD

**Issue by anaivebird** [a1ext/labeless#56]
I found import and analysis so slow, and even make ida stuck:
My solution is:
1. move idb file to ramdisk
2. close all windows, especially fuction、import windows, since it will sort all functions which consume much CPU.
   However, after labeless import each segmentation, it will automatically open import and function windows, which will grealy slow down.

So, how could I modify labeless to prevent it auto open  import and function windows?
Thanks.

**Comment by a1ext** [comment]
The plugin opens only imports window... Actually there is no way to prevent that out of the box. 
If you want to make it possible - you can send a PR

**Comment by anaivebird** [comment]
Thanks, I got it.
