### ISSUE TITLE
IDA 7.5 with Python 3.9.2 fails on loading Labeless DLL

### ISSUE THREAD

**Issue by sisoma2** [a1ext/labeless#58]
Hi Alex,

Installing the new version of Python and Labeless I've found problems trying to make them work properly in IDA 7.5. As I recall, with Python 3.9.1 the plugin worked.

### Environment
Python 3.9.2 x64
IDA 7.5

#### IDA-side information 

| Question                      | Answer
|-------------------------------|--------------------
| IDA-side OS version           | Win 10
| IDA plugin version            | build_1.1.2.121
| IDA PRO bitness (not IDB/I64) | 32, 64
| IDA plugin bitness            | 32, 64

### Problem Description
IDA Fails on loading Labeless DLL it says it's not a valid Win32 application

![imagen](https://user-images.githubusercontent.com/7660940/108984409-2d299480-7690-11eb-98dd-4ac65a1ee305.png)

**Comment by a1ext** [comment]
Hi, Python 3 is not supported yet.

**Comment by sisoma2** [comment]
So I need to install Python2 in the host machine to run the Labeless plugin in IDA? But If I recall the plugin worked fine with IDAPython in the Python3 version...

**Comment by a1ext** [comment]
Nope, I haven't implemented Python3 support so far. And I don't plan to do it until IDA supports Python 2. 
P.S. don't forget to switch python 3 to 2 via IDA's bundled tool
