### ISSUE TITLE
Hello,labeless fail to load

### ISSUE THREAD

**Issue by Kasi** [a1ext/labeless#60]
![image](https://user-images.githubusercontent.com/56646472/119587193-bf147b00-be00-11eb-850a-a2dce9a431d8.png)

How to solve this problem？thanks!

**Comment by Kasi** [comment]
![image](https://user-images.githubusercontent.com/56646472/119594234-f8071c80-be0d-11eb-8768-880a919c5367.png)
this is my system version.

**Comment by a1ext** [comment]
Hi @Kasi , which x64dbg do you use, 32-bit or 64-bit? what version? did you follow [installation instructions](https://github.com/a1ext/labeless#installation)?

**Comment by Kasi** [comment]
> Hi @Kasi , which x64dbg do you use, 32-bit or 64-bit? what version? did you follow [installation instructions](https://github.com/a1ext/labeless#installation)?

![image](https://user-images.githubusercontent.com/56646472/119658244-7f30b080-be5f-11eb-962f-25e519a39dd4.png)
I should have watched this tutorial earlier and now the problem is solved. 
The labeless has started working properly. Thank you!

**Comment by Kasi** [comment]
Problem being solved...

**Comment by a1ext** [comment]
You are welcome, enjoy :)
