### ISSUE TITLE
Labeless not showing in x64DBG

### ISSUE THREAD

**Issue by mhanne0915** [a1ext/labeless#7]
Hi, first of all thanks for the great plugin. I tried to use x64DBG butI noticed that labeless plugin is not showing in the plugin toolbar. I used the x64DBG included in your package but it doesn't work.
OS: Windows 7 SP1

**Comment by a1ext** [comment]
Thanks.
Do you see in the log window some errors in the log window, could you attach the log window content here?
Which of x64dbg type (x32 or x64) doesn't not work for you?
Are you performed setup instructions described in readme ?

**Comment by mhanne0915** [comment]
Here's the two test I did:

1. I used the x64DBG from labeless package (labeless_release_full_1.1.0.3\x64dbg). When I open the debugger, the labeless plugin didn't show.
Note: I changed the luncher config of x96dbg.ini because the default is:
            x32dbg=E:\_malware\labeless_release_full_1.1.0.3\x64dbg\x32\x32dbg.exe
            x64dbg=E:\_malware\labeless_release_full_1.1.0.3\x64dbg\x64\x64dbg.exe

2. I downloaded the latest x64DBG, and just put the labeless plugins (/x32/plugins/labeless_x64dbg.dp32 and /x64/plugins/labeless_x64dbg.dp64) in the plugins folder. I got an error message, see attached.

Btw, I'm not sure if is related to python version, but labeless works fine in Olly. Here's the python version I'm using:
       ActivePython 2.7.10.12 (ActiveState Software Inc.) based on Python 2.7.10 (default, Aug 21 2015,      
       14:42:12) [MSC v.1500 32 bit (Intel)] on win32
![scenario1](https://cloud.githubusercontent.com/assets/7477148/15936188/9f25a3d0-2e9c-11e6-8369-43774a831566.png)
![scenario2](https://cloud.githubusercontent.com/assets/7477148/15936187/9f253d28-2e9c-11e6-83a1-9fce8802a437.png)

**Comment by a1ext** [comment]
The version 1.1.0.3 is incompatible with latest x64dbg. Please, try ver [1.1.0.4](https://github.com/a1ext/labeless/releases).
starting from version 1.1.0.1 I added x64dbg snapshot to the release bundle, on which I test Labeless. I do that because x64dbg plugin API occasionally changes (in active development).
Let me know is 1.1.0.4 works.

**Comment by mhanne0915** [comment]
Thanks @a1ext a lot. It works fine ;) Sorry for wasting your time, I dunno why I didn't downloaded the latest version. Have a nice day.

**Comment by a1ext** [comment]
Thank you, don't hesitate to ask questions, report bugs or give your suggestions/feedback :smile_cat:
So, I'll close the issue.
