### ISSUE TITLE
Labeless and IDA repeatable comments

### ISSUE THREAD

**Issue by trietptm** [a1ext/labeless#8]
The current latest release of Labeless doesn't sync repeatable comments from IDA.
![screenshot - 6_22_2016 6_55_26 pm](https://cloud.githubusercontent.com/assets/526959/16265795/849e5aac-38ab-11e6-93f6-d99135d8bcee.png)

![screenshot - 6_22_2016 6_57_19 pm](https://cloud.githubusercontent.com/assets/526959/16265796/84b2dd92-38ab-11e6-98a4-b93df319f345.png)

![screenshot - 6_22_2016 7_02_58 pm](https://cloud.githubusercontent.com/assets/526959/16265883/0861c57c-38ac-11e6-9298-dfce224d8b2a.png)

**Comment by a1ext** [comment]
Thanks, I'll check that

**Comment by a1ext** [comment]
Hi @trietptm,
Could you re-check this issue on the [1.1.0.7 build](https://github.com/a1ext/labeless/releases/tag/v_1_1_0_7)

**Comment by a1ext** [comment]
So, I close the issue.
